export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_ITEM = 'DELETE_ITEM'
export const MINUS_QUALITY = 'MINUS_QUALITY'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'