export const ADD_TO_CART = 'ADD_TO_CART'
export const DELETE_ITEM = 'DELETE_ITEM'
export const MINUS_QUALITY = 'MINUS_QUALITY'

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE ALERT'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const USER_LOADED = 'USER_LOADED'
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'
